---
- hosts: "{{ hosts | default('dockerhosts') }}"
  gather_facts: True
  vars:
    _docker_image_name: base_docker_image
    image_tags: []

  tasks:
    - name: Share derived variables
      set_fact:
        docker_image_name: "{{ _docker_image_name }}"
        image_tags: "{{ git_branch_name.startswith('feature') | ternary( image_tags | union ( ['unstable'] ), image_tags ) }}"

    - name: Check for develop
      set_fact:
        image_tags: "{{ (git_branch_name == 'develop') | ternary( image_tags | union ( ['latest'] ), image_tags ) }}"

    - name: Check for master
      set_fact:
        image_tags: "{{ (git_branch_name == 'master') | ternary( image_tags | union ( ['release'] ), image_tags ) }}"

    - name: Render dockerfile from template
      template:
        src: "{{ docker_template_file }}"
        dest: "{{ docker_dockerfile_path }}/Dockerfile"
        mode: 0775
      when: docker_template_file is defined

    - name: Create image from dockerfile
      shell: |
        docker build \
        --force-rm \
        --tag "build_{{ docker_image_name }}:{{ docker_image_tag }}" \
        "{{ docker_dockerfile_path }}"

    - name: Run docker image for additional configuration
      command:
        argv:
          - docker
          - run
          - --name=build_tmp
          - --publish-all=true
          - --detach
          - "build_{{ docker_image_name }}:{{ docker_image_tag }}"
      register: build_image_id

    - name: Get exposed port on localhost
      command:
        argv:
          - docker
          - port
          - "{{ build_image_id.stdout }}"
          - "22"
      register: build_image_ssh_port

    - name: Add host to hosts list to process
      add_host:
        name: "127.0.0.1:{{ build_image_ssh_port.stdout.split(':')[1] }}"
        groups: just_created


- hosts: "just_created"
  gather_facts: False
  vars:
    ansible_user: sk_deploy

  roles:
    - semantiknit.base-docker-image

- hosts: "{{ hosts | default('dockerhosts') }}"
  gather_facts: false

  tasks:
    - name: create a docker image from the container
      command:
        argv:
          - docker
          - commit
          - -c
          - EXPOSE 22
          - -c
          - CMD /usr/sbin/sshd -D
          - build_tmp
          - "{{ docker_image_name }}:{{ docker_image_tag }}"

    - name: stop build container
      command:
        argv:
          - docker
          - stop
          - build_tmp

    - name: remove build container
      command:
        argv:
          - docker
          - rm
          - build_tmp

    - name: Remove existing tagged images if exist
      shell: |
        docker image rm \
        "{{ docker_image_name }}:{{ item }}"
      ignore_errors: yes
      with_items: "{{ image_tags }}"

    - name: Add additional tags to image
      shell: |
        docker tag \
        "{{ docker_image_name }}:{{ docker_image_tag }}" \
        "{{ docker_image_name }}:{{ item }}"
      with_items: "{{ image_tags }}"


