---
dependencies:
  - geerlinguy.java

galaxy_info:
  author: jinksunk
  description: Pellet for Linux Systems
  company: "Semantiknit, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - development
    - system
    - web
    - java
    - jdk
    - openjdk
    - oracle
    - pellet
