---

# Need to:
# 1. Ensure ssh is installed and listening
# 2. Generate a key to use for remote access and store somewhere / add to
#    authorized keys for a user
# 3. Add public key to authorized keys for public access endpoint
# 4. On first connect, add trusted host?
# 5. Add cron entry to run tunnel check every X minutes

- name: Install SshD
  become: yes
  become_user: root
  apt:
    name: openssh-server
    state: present
    update_cache: true
  notify:
   - Start Openssh
- name: Get current username
  local_action: command whoami
  register: local_username
- name: Create ssh key
  user:
    name: "{{ local_username }}"
    generate_ssh_key: yes        # Will not overwrite if already present
- name: Add ssh remote tunnel cron file
  become: yes
  become_user: root
  copy:
    src: remote-ssh.sh
    dest: /usr/local/bin/remote-ssh.sh
    owner: "{{ local_username }}"
    mode: u=rx,g=rx,o=rx
- name: Add cron job to check tunnel every 5 minutes
  become: yes
  become_user: "{{ local_username }}"
  cron:
    minute: */5
    job: /usr/local/bin/remote-ssh.sh "{{ remote_host_name }}" "{{ remote_port_number }}"
