---

# Need to:
# 1. Ensure ssh is installed and listening
# 2. Generate a key to use for remote access and store somewhere / add to
#    authorized keys for a user
# 3. Add public key to authorized keys for public access endpoint
# 4. On first connect, add trusted host?
# 5. Add cron entry to run tunnel check every X minutes

- name: Install SshD
  become: yes
  become_user: root
  apt:
    name: openssh-server
    state: present
    update_cache: true
  notify:
   - Start Openssh
