---
- name: Provision using docker playbook
  import_playbook: ../provision/docker-container-provision.yml
  vars:
    docker_image_name: example_website
    docker_publish_ports:
      - 22
      - 80
      - 443
    roles_to_apply:
      - semantiknit.example-website


- hosts: webdispatchers
  gather_facts: false
  vars:
    web_proxies_enabled:
      - name: example-website
        servername: localhost
        portnum: "{{ image_http_port.stdout.split(':')[1]  }}"

  roles:
    - semantiknit.web-enable-resources

