---
# file: deployexternal.yml
# List of playbooks that have an external deploy triggers
- hosts: webservers
  roles:
    - common
    - semantiknit.vpnserver

- hosts: vpnservers
  roles:
    - common
    - semantiknit.vpnserver
